### ISSUE TITLE
Send a message to a single client

### ISSUE THREAD

**Issue by wiesson** [kennethreitz/flask-sockets#15]
How could I send a message to a single client that is connected? I'm looking for something to send a notification to a logged in user that something is ready or so. Ideas?

**Comment by kennethreitz** [comment]
Here's an example backend you can get started with: https://github.com/heroku-examples/python-websockets-chat/blob/master/chat.py#L28

**Comment by ThisIsQasim** [comment]
I am following the above example and a little help would be appreciated. How do I distinguish between channels? And can I send messages from other functions?

**Comment by ThisIsQasim** [comment]
I am following the above example and a little help would be appreciated. I want to send messages to a single client only. How do I distinguish between clients? Can I assign identifiers to clients and select a client based on an id? For example when in the `run` function instead of `for client in self.clients:` I would want something like `client=self.client_by_id(id)`. Or should I just make a new channel for every socket?
